--- TRANSACTION_LINES table by ACCOUNTING_PERIOD
SELECT tl.*
FROM TRANSACTION_LINES tl
LEFT JOIN TRANSACTIONS t
       ON t.TRANSACTION_ID = tl.TRANSACTION_ID
LEFT JOIN ACCOUNTING_PERIODS ap
       ON ap.ACCOUNTING_PERIOD_ID = t.ACCOUNTING_PERIOD_ID
WHERE
    ap.NAME = 'Jan 2019';